bugfix/NETEXP-1452: Made Account Username uneditable
Telecominfraproject/wlan-cloud-ui-library pull request #220
Opened 2021-04-19 21:47 UTC by toando-netexperience

JIRA: [NETEXP-1452](https://connectustechnologies.atlassian.net/browse/NETEXP-1452)

## Description
*Summary of this PR*
bug:  when editing username and role error occurs with an error response `Cannot update user that does not Exist`

Solution: From cmap YAML `/portal/cmapPortalUser` states only roles can be changed. So made the username uneditable. 

### Before this PR
*Screenshots of what it looked like before this PR*
![Screen Shot 2021-04-19 at 5 46 45 PM](https://user-images.githubusercontent.com/70719869/115307476-40f4f280-a137-11eb-9f68-a8cec008d2d4.png)

### After this PR
*Screenshots of what it will look like after this PR*
![Screen Shot 2021-04-19 at 5 40 08 PM](https://user-images.githubusercontent.com/70719869/115307420-27ec4180-a137-11eb-9db1-cfd1fa86c00d.png)

2021-04-19 21:54 UTC, sean-macfarlane requested changes

2021-04-19 21:54 UTC, sean-macfarlane commented on src/containers/Accounts/components/FormModal/index.js
> +        {isAuth0Enabled && title === 'Edit User' ? (
why  the `&& title === 'Edit User'` ?

2021-04-20 14:39 UTC, sean-macfarlane approved these changes

2021-04-20 14:49 UTC, Irtiza-h30 approved these changes

2021-04-20 14:58 UTC, merged