Feature: Added extraIcon prop on ap details
Telecominfraproject/wlan-cloud-ui-library pull request #222
Opened 2021-04-20 21:14 UTC by toando-netexperience

JIRA: [NO JIRA](LINK)

## Description
*Summary of this PR*
- added `extraIcon` prop to the ap details page

### Before this PR
*Screenshots of what it looked like before this PR*

### After this PR
*Screenshots of what it will look like after this PR*

2021-04-20 22:42 UTC, Irtiza-h30 approved these changes

2021-04-21 19:13 UTC, sean-macfarlane requested changes

2021-04-21 19:13 UTC, sean-macfarlane commented on src/containers/AccessPointDetails/index.js
> +  extraIcon,
rename this prop as `avatar` this isn't 'extra' it's an override prop not adding

2021-04-21 21:10 UTC, sean-macfarlane approved these changes

2021-04-21 21:10 UTC, merged