bugfix/WIFI-2414: Added validation to roamingOI field
Telecominfraproject/wlan-cloud-ui-library pull request #239
Opened 2021-05-27 20:36 UTC by Irtiza-h30

JIRA: [WIFI-2414](https://telecominfraproject.atlassian.net/browse/WIFI-2414)

## Description
*Summary of this PR*

- Added validation to roamingOI field so that each sub-element in the field must be 3-15 octets in length (octet is a pair of hex characters, e.g. A3), and no duplicate elements can be inputted
- Improved UI of field to make it a dynamic list instead of a comma separated input field

### Before this PR
*Screenshots of what it looked like before this PR*
![image](https://user-images.githubusercontent.com/55258316/119893501-71376a00-bf09-11eb-9d70-a3333d897e09.png)

### After this PR
*Screenshots of what it will look like after this PR*
![image](https://user-images.githubusercontent.com/55258316/119893447-5ebd3080-bf09-11eb-9c03-8b913b088fc0.png)

2021-05-28 16:29 UTC, sean-macfarlane requested changes

2021-05-28 16:29 UTC, sean-macfarlane commented on src/containers/ProfileDetails/components/ProviderId/tests/index.test.js
> +const generateRandomHex = size =>
you can use faker `faker.random.hexaDecimal(8)`

2021-05-31 20:12 UTC, hassan-netex approved these changes

2021-05-31 20:48 UTC, sean-macfarlane approved these changes

2021-05-31 20:48 UTC, merged