hotfix/WIFI-789: Updated selection fill & button box fill
Telecominfraproject/wlan-cloud-ui-library pull request #80
Opened 2020-09-25 15:42 UTC by toando-netexperience

JIRA: [WIFI-789](https://telecominfraproject.atlassian.net/browse/WIFI-789)

## Description
*Summary of this PR*
- updated selection fill to be default blue and transparent
- updated button box fill to remain filled dark

### Before this PR
*Screenshots of what it looked like before this PR*
<img width="1792" alt="Screen Shot 2020-09-25 at 11 39 32 AM" src="https://user-images.githubusercontent.com/70719869/94287180-fb1ad780-ff23-11ea-9999-9910346e0d89.png">

### After this PR
*Screenshots of what it will look like after this PR*
<img width="1792" alt="Screen Shot 2020-09-25 at 11 40 03 AM" src="https://user-images.githubusercontent.com/70719869/94287204-0241e580-ff24-11ea-85a7-17111cb0bc7d.png">

2020-09-25 21:54 UTC, sean-macfarlane requested changes

2020-09-25 21:54 UTC, sean-macfarlane commented on src/containers/Dashboard/components/LineChart/index.module.scss
> +}
no newline at end of file. format your code when you save

2020-09-25 21:55 UTC, sean-macfarlane commented
This is only half of the bug. Look at the video attached in the JIRA

2020-09-28 16:30 UTC, toando-netexperience commented
Couldn't reproduce the 2nd half of the video, the highlighting issue

2020-09-29 16:51 UTC, sean-macfarlane approved these changes

2020-09-29 16:51 UTC, merged